baseURL: https://opengento.github.io/
languageCode: fr-fr
title: OpenGento - Communauté de développeurs ecommerce
theme: site-opengento-theme

params:
  hero:
    tagline: OpenGento
    subTagline: OpenGento est une association Française loi 1901 dont l'objet est l'organisation d'événements Magento pour la communauté de développeurs.
    buttonText: En savoir plus
    buttonUrl: /association-opengento/
    image: illustrations/worker.svg
    bottomIcons:
    - partners/adexos-150x65.png
    - partners/blackbird-logo.png
    - partners/hyva-small.png
    - partners/lumao-small.png
    - partners/mollie.png
    - partners/MonsieurBiz.png
    - partners/nola-consulting-logo.jpeg
    - partners/ph2m-logo.png
  navbar:
    name: OpenGento
    buttonText: Adhésion
    buttonUrl: https://www.helloasso.com/associations/opengento/adhesions/adhesion-individuelle-opengento
    logo:
      src: logos/opengento-150x150.png
      alt: OpenGento logo
    links:
    - text: Événements
      url: /events/
    - text: L’association
      url: /association-opengento/
  sidebar:
    columns:
    - title: OpenGento
      links:
      - name: L'association
        url: "/association-opengento/"
      - name: Adhésion individuelle
        url: https://www.helloasso.com/associations/opengento/adhesions/adhesion-individuelle-opengento
      - name: Adhésion entreprise
        url: https://www.helloasso.com/associations/opengento/adhesions/adhesion-entreprise-opengento
      - name: Mentions légales
        url: "/mentions-legales/"
    - title: Événements
      links:
      - name: Organisez un événement
        url: "/events/organisez-votre-evenement/"
      - name: Weekend OpenGento Sélestat 2024
        url: "/events/weekend-opengento-selestat-2024/"
      - name: Weekend OpenGento Toulouse 2024
        url: "/events/weekend-opengento-2024/"
      - name: Weekend OpenGento Toulouse 2022
        url: "/events/weekend-opengento-2022/"
      - name: Weekend OpenGento Béthune 2019
        url: "/events/weekend-opengento-2019/"
      - name: Weekend OpenGento Allègre 2018
        url: "/events/weekend-opengento-2018/"
      - name: Weekend OpenGento Toulouse 2017
        url: "/events/weekend-opengento-2017/"
      - name: Weekend OpenGento Toulouse 2016
        url: "/events/weekend-opengento-2016/"
      - name: Weekend OpenGento Toulouse 2015
        url: "/events/weekend-opengento-2015/"
    - title: Adhérents
      links:
      - name: Présentation
        url: "/adherents"
      - name: Adhésion individuelle
        url: https://www.helloasso.com/associations/opengento/adhesions/adhesion-individuelle-opengento
      - name: Adhésion entreprise
        url: https://www.helloasso.com/associations/opengento/adhesions/adhesion-entreprise-opengento
    - title: Open Source
      links:
      - name: Découvrez nos modules !
        url: "/projects"
    followUs:
    - icon: github
      url: "https://github.com/opengento"
    - icon: twitter
      url: "https://twitter.com/opengento"
    - icon: linkedin
      url: "https://linkedin.com/company/opengento"
  features:
    tagline: Événements OpenGento
    subTagline: Prochains événements organisés par OpenGento
    panels:
    - title: Meet Magento France 2024
      image: icons/calendar.svg
      text: Mardi 25 Mars 2025 à Paris
      button:
        text: En savoir plus
        url: "https://fr.meet-magento.com/"
      delay: 1
    - title: Week-end 2025
      image: icons/add.svg
      text: Soyez le prochain à organiser l'évènement dans votre région !
      button:
        text: En savoir plus
        url: "/events/organisez-votre-evenement/"
      delay: 2
  contact:
    tagline: Drop us a line or two!
  footer:
    image: opengento-300x300.png
    columns:
    - title: OpenGento
      links:
      - name: L'association
        url: "/association-opengento/"
      - name: Organisez un événement
        url: "/events/organisez-votre-evenement/"
      - name: Mentions légales
        url: "/mentions-legales/"
    - title: Événements
      links:
      - name: Weekend OpenGento Sélestat 2024
        url: "/events/weekend-opengento-selestat-2024/"
      - name: Weekend OpenGento 2024
        url: "/events/weekend-opengento-2024/"
      - name: Weekend OpenGento 2022
        url: "/events/weekend-opengento-2022/"
      - name: Weekend OpenGento 2019
        url: "/events/weekend-opengento-2019/"
      - name: Weekend OpenGento 2018
        url: "/events/weekend-opengento-2018/"
      - name: Weekend OpenGento 2017
        url: "/events/weekend-opengento-2017/"
      - name: Weekend OpenGento 2016
        url: "/events/weekend-opengento-2016/"
      - name: Weekend OpenGento 2015
        url: "/events/weekend-opengento-2015/"
    followUs:
    - icon: github
      url: "https://github.com/opengento"
    - icon: twitter
      url: "https://twitter.com/opengento"
    - icon: linkedin
      url: "https://linkedin.com/company/opengento"
